# Generated by Django 5.2.12 on 2026-04-22 11:54

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_campus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(blank=True, upload_to=tickets.models.ticket_image_upload_path),
        ),
    ]
