# Generated by Django 5.2.12 on 2026-05-28 21:51

import tickets.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_alter_ticket_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeeklyReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('week_start', models.DateTimeField(verbose_name='Początek tygodnia')),
                ('week_end', models.DateTimeField(verbose_name='Koniec tygodnia')),
                ('content', models.TextField(blank=True, null=True, verbose_name='Wygenerowany raport AI')),
                ('raw_stats', models.JSONField(default=dict, verbose_name='Surowe Statystyki JSON')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Utworzono')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='ticket',
            name='image',
            field=models.ImageField(upload_to=tickets.models.ticket_image_upload_path),
        ),
    ]
