# Generated by Django 5.2.12 on 2026-04-06 12:51

from django.db import migrations


def create_default_groups(apps, schema_editor):
    Group = apps.get_model('auth', 'Group')
    Group.objects.get_or_create(name='REPORTER')
    Group.objects.get_or_create(name='COORDINATOR')

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_groups),
    ]
